// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5eVnwtA3efMBS4CVFyk5UdZaw8IKngec',
    appId: '1:112386856875:web:cfd43b0860a84247ce24ee',
    messagingSenderId: '112386856875',
    projectId: 'ditonton-app-656b7',
    authDomain: 'ditonton-app-656b7.firebaseapp.com',
    storageBucket: 'ditonton-app-656b7.appspot.com',
    measurementId: 'G-SEDMW9DSRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw5eCCAI8g47ieX8ftST576s8yN1otHlo',
    appId: '1:112386856875:android:27038d743a581e9bce24ee',
    messagingSenderId: '112386856875',
    projectId: 'ditonton-app-656b7',
    storageBucket: 'ditonton-app-656b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA58Bt9tEkUGjSs7oETFyW3wKZjC-gWyrU',
    appId: '1:112386856875:ios:3db8ee9c0b472772ce24ee',
    messagingSenderId: '112386856875',
    projectId: 'ditonton-app-656b7',
    storageBucket: 'ditonton-app-656b7.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
